# Generated by Django 4.1.2 on 2022-11-15 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(default='New', max_length=50)),
                ('releaseDateTime', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=5)),
                ('isApproved', models.BooleanField(default=True, help_text='Approve the album if its name is not explicit')),
                ('Artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artists')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Image', models.ImageField(upload_to='')),
                ('Audio', models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('Albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
            ],
        ),
    ]
