# Generated by Django 4.1.2 on 2022-10-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='New', max_length=50)),
                ('creationDateTime', models.DateTimeField()),
                ('releaseDateTime', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artists')),
            ],
        ),
    ]
