# Generated by Django 4.1.2 on 2022-10-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='isApproved',
            field=models.BooleanField(default=True, help_text='Approve the album if its name is not explicit'),
        ),
    ]
