# Generated by Django 4.1.2 on 2022-10-26 23:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_albums_creationdatetime_albums_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Albums.Name', max_length=50)),
                ('Image', models.ImageField(upload_to='')),
                ('Audio', models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('Albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
            ],
        ),
    ]
