# Generated by Django 4.1.2 on 2022-10-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
